server:
  port: 8080
  servlet:
    context-path: /api

spring:
  config:
    activate:
      on-profile: "dev"
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:public.key
  datasource:
    url: jdbc:mysql://localhost:3306/english_center_management?createDatabaseIfNotExist=true
    username: root
    password: NguyenVanSuong@2001
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
  jackson:
    default-property-inclusion: always
  liquibase:
    user: root
    password: NguyenVanSuong@2001
logging:
  ignores-path:
    - "/api/resources/**"
security:
  private-key-location: classpath:private.key
  jwt-time: 15M
  cors:
    url: http://localhost:4200

schedule:
  timetable:
    change-status:
      enabled: false
      cron: '0 * * ? * *'

resource:
  provider: local
  local:
    path: 'D:\sp\english_center_management\english-center-management-be\asserts'
    host: http://localhost:${server.port}${server.servlet.context-path}/asserts